package interfaz;

public enum MenuAdmin {
    VER_RECAUDACION_DEL_DIA, 
    VER_TICKET_POR_TIPODEPAGO,
    VER_VENTAS_DEL_DIA,
    CONTRATAR_CAMARERO, 
    DESPEDIR_CAMARERO, 
    AGREGAR_PLATO,
    ELIMINAR_PLATO,
    ATRAS
    
}
